import './AboutContent.scss'

const AboutContent = () => {
  return (
    <div className='about-content'>
      <h2>Description de l’agence</h2>
      <p><b>Lucas Devienne</b> est un jeune architecte diplômé d’État en 2020 par l'<b>ENSAPLV</b> qui obtient habilité à la maîtrise d'ouvrage en 2025. Il fonde l'agence <b>EC</b> (Espace Construction Architecture) en 2026 dans la continuité d'expériences professionnelles menées au sein d'agences basées en <b>région parisienne</b> et en <b>Guadeloupe</b>. Cette initiative a également été nourrie par le développement d'une pratique plus personnelle, notamment en termes de conception architecturale.</p>

      <h2>Exigence conceptuelle et processus de projet</h2>
      <p>La démarche conceptuelle de l'agence implique de définir un <b>sens</b> donné au projet architectural. Ce sens se traduit par la formation d'un <b>schéma de conception</b>, une résolution formelle des problématiques esthétiques et fonctionnelles du projet tout en y apportant une direction lisible et claire. À l'image d'un ensemble de pièces, ce schéma définit la façon de transcrire le <b>programme</b> et les <b>intentions spatiales</b> du projet. Ces critères de conception suggèrent une application à toutes les échelles, celle du territoire en faisant participer le paysage à la composition du projet, celle de l'édifice en utilisant la structure comme marqueur du dimensionnement et de la volumétrie du projet, celle de la pièce en conditionnant les proportions des espaces et leurs transitions ou encore celle du détail transformant la complexité constructive en expression de l'architecture.</p>

      <p>La notion de schéma implique également de garder de la <b>flexibilité</b> au projet tout en préservant les critères de conception. Elle permet de rester à l'écoute de la maîtrise d'ouvrage, de leur demande vis-à-vis des modes d'habiter, de leurs goûts, de leurs expériences et de leurs références. Il est question de faire <b>participer</b> la maîtrise d'ouvrage lors des phases de conception tout en préservant le cap. Cette flexibilité est également à l'épreuve des <b>transformations</b> qui surviendront tout au long du processus de projet. Entre la phase esquisse, l'instruction du permis de construire, la consultation des entreprises et l'exécution des travaux, le projet architectural subit des évolutions qui, lorsqu'il est bien pensé, doivent toujours s'intégrer dans le schéma de conception.</p>

      <h2>Le climat comme ressource dans l’architecture	</h2>
      <p>L'expérience de l'agence aux <b>Antilles Françaises</b> dans le cadre de bon nombre de ses projets nous a permis de développer un regard particulier sur les <b>composantes climatiques</b> d'un site. Utiliser le climat comme ressource lors de la conception d'un édifice nourrit des réflexions à tous les niveaux du projet, que ce soit en définissant le <b>comportement au vent</b> du bâtiment pour guider la ventilation naturelle, son <b>orientation</b> et ses protections solaires en relation avec les usages donnés aux pièces, la <b>gestion de la pluie</b> et de l'humidité pour caractériser les aspects constructifs de l'enveloppe. Toutes ces composantes climatiques fournissent des <b>pistes de conception</b> qui peuvent aller jusqu'à définir la matérialité d'un projet. L'étude du climat dans une région donnée permet donc de caractériser une architecture contextualisée, confortable à vivre et résistante à long terme.</p>

      <h2>Gestion constructive et économique du projet</h2>
      <p>Les compétences de l'agence se traduisent également par une volonté de <b>maîtrise technique</b>, en anticipation des problématiques constructives tout au long du processus de projet. Le <b>travail du détail</b> dès les phases de conception prépare le passage à l'<b>acte de bâtir</b>. Notre vision du détail consiste à le considérer comme un outil permettant à un moment du projet traduisant une difficulté constructive de devenir une source d'expression dans l'architecture. Il a donc un rôle à jouer lors des phases de conception, en résolvant l'équilibre entre <b>forme idéalisée</b> du projet et <b>réalité construite</b>. Cette démarche nous pousse à intégrer les entreprises dans les échanges bien avant de préparer la demande de permis de construire. Cet apport a également l'avantage de rassurer la maîtrise d'ouvrage sur l'économie de projet et la <b>gestion du chantier</b> en leur offrant la garantie d'une association avec un réseau professionnel compétent. L'anticipation des problématiques constructives en phase de conception est également gage d'un chantier qui respectera les délais.</p>
    </div>
   )
}

export default AboutContent
